name: Backend CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITOPS_REPO: arnaudcedric/bank-gitops
  VALUES_FILE: values-dev.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Set Short SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/arnaudcedric/backend_bankapp_springboot:${{ env.SHORT_SHA }}
            ghcr.io/arnaudcedric/backend_bankapp_springboot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          ref: main
          path: gitops
          fetch-depth: 0

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE/gitops"

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      - name: Update Backend Image Tag
        shell: bash
        run: |
          echo "SHORT_SHA=${SHORT_SHA}"

          yq eval '.backend.image.tag = env(SHORT_SHA)' -i "gitops/${{ env.VALUES_FILE }}"

          echo "----- Updated file -----"
          cat "gitops/${{ env.VALUES_FILE }}"

      - name: Commit and Push GitOps Changes
        shell: bash
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add "${{ env.VALUES_FILE }}"

          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "Update backend image to ${SHORT_SHA}"
          git push
